###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  web:
    image: 'nginx:alpine'
    container_name: web
    working_dir: /app
    volumes:
      - '.:/app'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
    networks:
      - symfony-network

  php:
    build: phpdocker/php-fpm
    container_name: php
    working_dir: /app
    volumes:
      - '.:/app'
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge
