name: CI Symfony with Docker

on:
  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    build:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Docker
          run: |
            docker compose up -d --build
            docker ps -a
        - name: Files
          run: docker compose exec php-fpm ls -la

        - name: Run tests
          run: docker compose exec php-fpm  bin/phpunit

        - name: Docker down
          run: docker compose down


