name: CI - Docker Symfony

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: |
          docker compose up -d --build
          
      - name: Wait for containers
        run: sleep 5

      - name: Verify running containers
        run: docker ps -a

      - name: List fiels
        run: docker exec php-fpm ls -la

      - name: Install dependencies
        run: docker exec php-fpm composer install

      - name: Run tests
        run: docker exec php-fpm php bin/phpunit

      - name: Down containers
        run: |
          docker compose down 
